apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: echo
spec:
  sources:
    - content: |
       // package name is optional, but include in this example
       package com.foo;

       @org.apache.camel.BindToRegistry("echo")
       public class MyEchoBean {
         public String echo(String body) {
             return body + " " + body + "! from " + this.getClass().getName();
         }
       }
      name: MyEchoBean.java
  flows:
    - from:
        uri: "timer:yaml"
        parameters:
          period: "1000"
        steps:
          - setBody:
              constant: "Hello World"
          - bean:
              ref: "echo"
          - log: "${body}"
