# camel-k: language=yaml

# route configuration

- route-configuration:
    error-handler:
      dead-letter-channel:
        deadLetterUri: "log:dead"
        redeliveryPolicy: 
          maximumRedeliveries: 5
          retryAttemptedLogLevel: WARN
